version: '3.5'

services:
  backend:
      build: example-backend
      ports:
      - 8080:8080
      environment:
        - REDIS_HOST=redis
  frontend:
      build: example-frontend
      ports:
        - 5000:5000
  redis:
    image: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
