version: '3.5'

services:
  backend:
      build: example-backend
      environment:

      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      ports:
      - 8080:8080
  frontend:
      build: example-frontend
      ports:
        - 5000:5000
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=./database
  redis:
    image: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    working_dir: /opt/redis
    ports:
      - "6379:6379"
