version: '3.5'

services:
  backend:
      build: example-backend
      ports:
      - 8080:8080

  frontend:
      image: node:14-alpine
      build: example-frontend
      ports:
        - 5000:5000

